### ISSUE TITLE
Please update the download link of MitoFish

### ISSUE THREAD

**Issue by billzt** [Hobbeist/OceanOmics-amplicon#46]
https://github.com/Hobbeist/OceanOmics-amplicon/blob/93b4ebde71c40a5a59b68682f16ab40494aff775/scripts/download_mitofish.sh#L9

Change it to:

```
wget 'http://mitofish.aori.u-tokyo.ac.jp/species/detail/download/?filename=download/mitogenomes.zip' -O mitogenomes.zip
```

**Comment by philippbayer** [comment]
Thank you very much @billzt ! We'll change that this week :)

**Comment by Hobbeist** [comment]
Done. We have updated the link to the database. Thanks!
